update depdendencies for webpack 5
openlattice/lattice-ui-kit pull request #1258
Opened 2021-06-11 17:46 UTC by solomontang

- update dependencies to use webpack5
- move core lattice dependencies to peerDependencies

2021-06-11 18:23 UTC, UnsungHero97 requested changes

2021-06-11 18:23 UTC, UnsungHero97 commented on config/babel/babel.config.js
> +    }],
I based changes in our other libraries on this comment:

https://github.com/babel/babel/issues/9853#issuecomment-619587386

> If you are authoring a library, use only @babel/transform-runtime with corejs option plus @babel/runtime-corejs3 as dependency, and @babel/preset-env for syntax transpilation with useBuiltIns: false.

So this should be:

```
['@babel/preset-env', {
  useBuiltIns: false,
}],
```

2021-06-11 18:23 UTC, UnsungHero97 commented on config/webpack/webpack.config.js
> -    },
You added `webpack-node-externals` to `package.json` but you're not using it here.

2021-06-11 18:23 UTC, UnsungHero97 commented on package.json
> +    "redux-reqseq": "0.6.1"
This can be moved to externals.

2021-06-11 18:23 UTC, UnsungHero97 commented on package.json
> +    "@babel/runtime": "~7.14.5",
I don't think this is necessary because of `@babel/runtime-corejs3` in deps above.

2021-06-12 20:00 UTC, UnsungHero97 approved these changes

2021-06-16 00:18 UTC, anzioka approved these changes

2021-06-16 17:13 UTC, merged