APPS-2378 update button focus states and update stories
openlattice/lattice-ui-kit pull request #843
Opened 2020-10-10 03:42 UTC by bergieboy

### Button Design Updates
- updated focus states
- updated active states
- updated colors for both light and dark themes
- updated snapshots
- updated tests

### Contained
![Hnet com-image (4)](https://user-images.githubusercontent.com/19995069/95644971-82616280-0a6f-11eb-817e-c3cb27c3152f.gif)
### Outlined
![Hnet com-image (5)](https://user-images.githubusercontent.com/19995069/95645003-ae7ce380-0a6f-11eb-8077-a586331debb5.gif)
### Text
![Hnet com-image (6)](https://user-images.githubusercontent.com/19995069/95645021-db30fb00-0a6f-11eb-9b57-984bc7eeb14c.gif)

2020-10-16 18:12 UTC, UnsungHero97 requested changes
1. The default button doesn’t activate the outline on click, only shows up after you hover away vs primary button behaves how you would expect; same for the other variants.
2. There’s a nice gap between the box shadow on the “contained” variant, but it’s not there for the other variants:
<img width="110" alt="Screen Shot 2020-10-14 at 5 26 19 PM" src="https://user-images.githubusercontent.com/440299/96293882-575f9d00-0fa0-11eb-8614-7e663910554e.png"> <img width="106" alt="Screen Shot 2020-10-14 at 5 26 53 PM" src="https://user-images.githubusercontent.com/440299/96293885-57f83380-0fa0-11eb-8960-46fd97e03980.png">
3. Following up on 2, when you hover away, it looks like a double border:
<img width="148" alt="Screen Shot 2020-10-14 at 5 30 02 PM" src="https://user-images.githubusercontent.com/440299/96293934-68101300-0fa0-11eb-8185-5b5e10d6f4fd.png">

2020-10-22 16:40 UTC, UnsungHero97 requested changes
The default button doesn't behave like the others when tabbing through with the keyboard, i.e. the box shadow does not show up.

2020-10-23 20:05 UTC, UnsungHero97 approved these changes

2020-10-26 16:22 UTC, solomontang approved these changes

2020-10-27 22:17 UTC, merged